name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        cd client
        npm ci
        npm install @tensorflow/tfjs @tensorflow-models/universal-sentence-encoder
        cd ../server
        npm ci

    - name: Debug npm
      run: |
        cd client
        npm list

    - name: Build client
      run: |
        cd client
        npm run build

        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: ./.github/actions/deploy
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/dist
